//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  personalInfo: PersonalInfo;
  personalInfoConnection: PersonalInfoConnection;
  event: Event;
  eventConnection: EventConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  equipment: Equipment;
  equipmentConnection: EquipmentConnection;
  timeline: Timeline;
  timelineConnection: TimelineConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  showreelVideo: ShowreelVideo;
  showreelVideoConnection: ShowreelVideoConnection;
  faq: Faq;
  faqConnection: FaqConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPersonalInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPersonalInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PersonalInfoFilter>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryEquipmentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEquipmentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EquipmentFilter>;
};


export type QueryTimelineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTimelineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TimelineFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QueryShowreelVideoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShowreelVideoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShowreelVideoFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};

export type DocumentFilter = {
  personalInfo?: InputMaybe<PersonalInfoFilter>;
  event?: InputMaybe<EventFilter>;
  service?: InputMaybe<ServiceFilter>;
  equipment?: InputMaybe<EquipmentFilter>;
  timeline?: InputMaybe<TimelineFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  showreelVideo?: InputMaybe<ShowreelVideoFilter>;
  faq?: InputMaybe<FaqFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = PersonalInfo | Event | Service | Equipment | Timeline | Testimonial | ShowreelVideo | Faq | Folder;

export type PersonalInfoSocials = {
  __typename?: 'PersonalInfoSocials';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type PersonalInfo = Node & Document & {
  __typename?: 'PersonalInfo';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  portrait?: Maybe<Scalars['String']['output']>;
  showreelUrl?: Maybe<Scalars['String']['output']>;
  experienceYears?: Maybe<Scalars['Float']['output']>;
  eventsCount?: Maybe<Scalars['Float']['output']>;
  broadcastersCount?: Maybe<Scalars['Float']['output']>;
  uptimePercentage?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  whatsappUrl?: Maybe<Scalars['String']['output']>;
  workingHours?: Maybe<Scalars['String']['output']>;
  socials?: Maybe<Array<Maybe<PersonalInfoSocials>>>;
  degree?: Maybe<Scalars['String']['output']>;
  degreeHonors?: Maybe<Scalars['String']['output']>;
  statusText?: Maybe<Scalars['String']['output']>;
  statusTextShort?: Maybe<Scalars['String']['output']>;
  statusActive?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PersonalInfoSocialsFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PersonalInfoFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  portrait?: InputMaybe<StringFilter>;
  showreelUrl?: InputMaybe<StringFilter>;
  experienceYears?: InputMaybe<NumberFilter>;
  eventsCount?: InputMaybe<NumberFilter>;
  broadcastersCount?: InputMaybe<NumberFilter>;
  uptimePercentage?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  whatsappUrl?: InputMaybe<StringFilter>;
  workingHours?: InputMaybe<StringFilter>;
  socials?: InputMaybe<PersonalInfoSocialsFilter>;
  degree?: InputMaybe<StringFilter>;
  degreeHonors?: InputMaybe<StringFilter>;
  statusText?: InputMaybe<StringFilter>;
  statusTextShort?: InputMaybe<StringFilter>;
  statusActive?: InputMaybe<BooleanFilter>;
};

export type PersonalInfoConnectionEdges = {
  __typename?: 'PersonalInfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PersonalInfo>;
};

export type PersonalInfoConnection = Connection & {
  __typename?: 'PersonalInfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PersonalInfoConnectionEdges>>>;
};

export type EventSpecs = {
  __typename?: 'EventSpecs';
  format?: Maybe<Scalars['String']['output']>;
  visionMixer?: Maybe<Scalars['String']['output']>;
  replay?: Maybe<Scalars['String']['output']>;
  cameras?: Maybe<Scalars['String']['output']>;
  syncRouter?: Maybe<Scalars['String']['output']>;
  audioIntercom?: Maybe<Scalars['String']['output']>;
};

export type EventKeyStats = {
  __typename?: 'EventKeyStats';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type EventSignalFlow = {
  __typename?: 'EventSignalFlow';
  step?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type EventChallengesAndSolutions = {
  __typename?: 'EventChallengesAndSolutions';
  challenge?: Maybe<Scalars['String']['output']>;
  solution?: Maybe<Scalars['String']['output']>;
  impact?: Maybe<Scalars['String']['output']>;
};

export type Event = Node & Document & {
  __typename?: 'Event';
  slug: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  venue?: Maybe<Scalars['String']['output']>;
  broadcaster?: Maybe<Scalars['String']['output']>;
  dates?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  cameraCount?: Maybe<Scalars['Float']['output']>;
  specs?: Maybe<EventSpecs>;
  keyStats?: Maybe<Array<Maybe<EventKeyStats>>>;
  technicalApproach?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  signalFlow?: Maybe<Array<Maybe<EventSignalFlow>>>;
  challengesAndSolutions?: Maybe<Array<Maybe<EventChallengesAndSolutions>>>;
  outcomes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  improvementReflection?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventSpecsFilter = {
  format?: InputMaybe<StringFilter>;
  visionMixer?: InputMaybe<StringFilter>;
  replay?: InputMaybe<StringFilter>;
  cameras?: InputMaybe<StringFilter>;
  syncRouter?: InputMaybe<StringFilter>;
  audioIntercom?: InputMaybe<StringFilter>;
};

export type EventKeyStatsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type EventSignalFlowFilter = {
  step?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type EventChallengesAndSolutionsFilter = {
  challenge?: InputMaybe<StringFilter>;
  solution?: InputMaybe<StringFilter>;
  impact?: InputMaybe<StringFilter>;
};

export type EventFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  broadcaster?: InputMaybe<StringFilter>;
  dates?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  cameraCount?: InputMaybe<NumberFilter>;
  specs?: InputMaybe<EventSpecsFilter>;
  keyStats?: InputMaybe<EventKeyStatsFilter>;
  technicalApproach?: InputMaybe<StringFilter>;
  signalFlow?: InputMaybe<EventSignalFlowFilter>;
  challengesAndSolutions?: InputMaybe<EventChallengesAndSolutionsFilter>;
  outcomes?: InputMaybe<StringFilter>;
  improvementReflection?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type EquipmentItems = {
  __typename?: 'EquipmentItems';
  name?: Maybe<Scalars['String']['output']>;
  model?: Maybe<Scalars['String']['output']>;
  manufacturer?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  protocols?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  experienceYears?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
};

export type Equipment = Node & Document & {
  __typename?: 'Equipment';
  name: Scalars['String']['output'];
  iconName?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<EquipmentItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EquipmentItemsFilter = {
  name?: InputMaybe<StringFilter>;
  model?: InputMaybe<StringFilter>;
  manufacturer?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  protocols?: InputMaybe<StringFilter>;
  experienceYears?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type EquipmentFilter = {
  name?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<EquipmentItemsFilter>;
};

export type EquipmentConnectionEdges = {
  __typename?: 'EquipmentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Equipment>;
};

export type EquipmentConnection = Connection & {
  __typename?: 'EquipmentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EquipmentConnectionEdges>>>;
};

export type Timeline = Node & Document & {
  __typename?: 'Timeline';
  period: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  achievements?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  technologies?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TimelineFilter = {
  period?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  achievements?: InputMaybe<StringFilter>;
  technologies?: InputMaybe<StringFilter>;
};

export type TimelineConnectionEdges = {
  __typename?: 'TimelineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Timeline>;
};

export type TimelineConnection = Connection & {
  __typename?: 'TimelineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TimelineConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  quote: Scalars['String']['output'];
  author?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  organization?: Maybe<Scalars['String']['output']>;
  event?: Maybe<Scalars['String']['output']>;
  avatarText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  organization?: InputMaybe<StringFilter>;
  event?: InputMaybe<StringFilter>;
  avatarText?: InputMaybe<StringFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type ShowreelVideo = Node & Document & {
  __typename?: 'ShowreelVideo';
  title: Scalars['String']['output'];
  caption?: Maybe<Scalars['String']['output']>;
  thumb?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShowreelVideoFilter = {
  title?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  thumb?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
};

export type ShowreelVideoConnectionEdges = {
  __typename?: 'ShowreelVideoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ShowreelVideo>;
};

export type ShowreelVideoConnection = Connection & {
  __typename?: 'ShowreelVideoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShowreelVideoConnectionEdges>>>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  question: Scalars['String']['output'];
  answer?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePersonalInfo: PersonalInfo;
  createPersonalInfo: PersonalInfo;
  updateEvent: Event;
  createEvent: Event;
  updateService: Service;
  createService: Service;
  updateEquipment: Equipment;
  createEquipment: Equipment;
  updateTimeline: Timeline;
  createTimeline: Timeline;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updateShowreelVideo: ShowreelVideo;
  createShowreelVideo: ShowreelVideo;
  updateFaq: Faq;
  createFaq: Faq;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePersonalInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: PersonalInfoMutation;
};


export type MutationCreatePersonalInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: PersonalInfoMutation;
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateEquipmentArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipmentMutation;
};


export type MutationCreateEquipmentArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipmentMutation;
};


export type MutationUpdateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};


export type MutationCreateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdateShowreelVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: ShowreelVideoMutation;
};


export type MutationCreateShowreelVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: ShowreelVideoMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};

export type DocumentUpdateMutation = {
  personalInfo?: InputMaybe<PersonalInfoMutation>;
  event?: InputMaybe<EventMutation>;
  service?: InputMaybe<ServiceMutation>;
  equipment?: InputMaybe<EquipmentMutation>;
  timeline?: InputMaybe<TimelineMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  showreelVideo?: InputMaybe<ShowreelVideoMutation>;
  faq?: InputMaybe<FaqMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  personalInfo?: InputMaybe<PersonalInfoMutation>;
  event?: InputMaybe<EventMutation>;
  service?: InputMaybe<ServiceMutation>;
  equipment?: InputMaybe<EquipmentMutation>;
  timeline?: InputMaybe<TimelineMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  showreelVideo?: InputMaybe<ShowreelVideoMutation>;
  faq?: InputMaybe<FaqMutation>;
};

export type PersonalInfoSocialsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PersonalInfoMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  portrait?: InputMaybe<Scalars['String']['input']>;
  showreelUrl?: InputMaybe<Scalars['String']['input']>;
  experienceYears?: InputMaybe<Scalars['Float']['input']>;
  eventsCount?: InputMaybe<Scalars['Float']['input']>;
  broadcastersCount?: InputMaybe<Scalars['Float']['input']>;
  uptimePercentage?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  whatsappUrl?: InputMaybe<Scalars['String']['input']>;
  workingHours?: InputMaybe<Scalars['String']['input']>;
  socials?: InputMaybe<Array<InputMaybe<PersonalInfoSocialsMutation>>>;
  degree?: InputMaybe<Scalars['String']['input']>;
  degreeHonors?: InputMaybe<Scalars['String']['input']>;
  statusText?: InputMaybe<Scalars['String']['input']>;
  statusTextShort?: InputMaybe<Scalars['String']['input']>;
  statusActive?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventSpecsMutation = {
  format?: InputMaybe<Scalars['String']['input']>;
  visionMixer?: InputMaybe<Scalars['String']['input']>;
  replay?: InputMaybe<Scalars['String']['input']>;
  cameras?: InputMaybe<Scalars['String']['input']>;
  syncRouter?: InputMaybe<Scalars['String']['input']>;
  audioIntercom?: InputMaybe<Scalars['String']['input']>;
};

export type EventKeyStatsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type EventSignalFlowMutation = {
  step?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type EventChallengesAndSolutionsMutation = {
  challenge?: InputMaybe<Scalars['String']['input']>;
  solution?: InputMaybe<Scalars['String']['input']>;
  impact?: InputMaybe<Scalars['String']['input']>;
};

export type EventMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  broadcaster?: InputMaybe<Scalars['String']['input']>;
  dates?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  cameraCount?: InputMaybe<Scalars['Float']['input']>;
  specs?: InputMaybe<EventSpecsMutation>;
  keyStats?: InputMaybe<Array<InputMaybe<EventKeyStatsMutation>>>;
  technicalApproach?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  signalFlow?: InputMaybe<Array<InputMaybe<EventSignalFlowMutation>>>;
  challengesAndSolutions?: InputMaybe<Array<InputMaybe<EventChallengesAndSolutionsMutation>>>;
  outcomes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  improvementReflection?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type EquipmentItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  model?: InputMaybe<Scalars['String']['input']>;
  manufacturer?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  protocols?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  experienceYears?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EquipmentMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<EquipmentItemsMutation>>>;
};

export type TimelineMutation = {
  period?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  achievements?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  technologies?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TestimonialMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  event?: InputMaybe<Scalars['String']['input']>;
  avatarText?: InputMaybe<Scalars['String']['input']>;
};

export type ShowreelVideoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type PersonalInfoSocialsFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type PersonalInfoFilter = {
  name?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  heroHeadline?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  portrait?: StringFilter | null | undefined;
  showreelUrl?: StringFilter | null | undefined;
  experienceYears?: NumberFilter | null | undefined;
  eventsCount?: NumberFilter | null | undefined;
  broadcastersCount?: NumberFilter | null | undefined;
  uptimePercentage?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  whatsappUrl?: StringFilter | null | undefined;
  workingHours?: StringFilter | null | undefined;
  socials?: PersonalInfoSocialsFilter | null | undefined;
  degree?: StringFilter | null | undefined;
  degreeHonors?: StringFilter | null | undefined;
  statusText?: StringFilter | null | undefined;
  statusTextShort?: StringFilter | null | undefined;
  statusActive?: BooleanFilter | null | undefined;
};

export type EventSpecsFilter = {
  format?: StringFilter | null | undefined;
  visionMixer?: StringFilter | null | undefined;
  replay?: StringFilter | null | undefined;
  cameras?: StringFilter | null | undefined;
  syncRouter?: StringFilter | null | undefined;
  audioIntercom?: StringFilter | null | undefined;
};

export type EventKeyStatsFilter = {
  label?: StringFilter | null | undefined;
  value?: StringFilter | null | undefined;
};

export type EventSignalFlowFilter = {
  step?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type EventChallengesAndSolutionsFilter = {
  challenge?: StringFilter | null | undefined;
  solution?: StringFilter | null | undefined;
  impact?: StringFilter | null | undefined;
};

export type EventFilter = {
  slug?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  venue?: StringFilter | null | undefined;
  broadcaster?: StringFilter | null | undefined;
  dates?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  heroImage?: StringFilter | null | undefined;
  gallery?: StringFilter | null | undefined;
  videoUrl?: StringFilter | null | undefined;
  summary?: StringFilter | null | undefined;
  cameraCount?: NumberFilter | null | undefined;
  specs?: EventSpecsFilter | null | undefined;
  keyStats?: EventKeyStatsFilter | null | undefined;
  technicalApproach?: StringFilter | null | undefined;
  signalFlow?: EventSignalFlowFilter | null | undefined;
  challengesAndSolutions?: EventChallengesAndSolutionsFilter | null | undefined;
  outcomes?: StringFilter | null | undefined;
  improvementReflection?: StringFilter | null | undefined;
  tags?: StringFilter | null | undefined;
};

export type ServiceFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type EquipmentItemsFilter = {
  name?: StringFilter | null | undefined;
  model?: StringFilter | null | undefined;
  manufacturer?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  protocols?: StringFilter | null | undefined;
  experienceYears?: NumberFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
};

export type EquipmentFilter = {
  name?: StringFilter | null | undefined;
  iconName?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  items?: EquipmentItemsFilter | null | undefined;
};

export type TimelineFilter = {
  period?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  company?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  type?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  achievements?: StringFilter | null | undefined;
  technologies?: StringFilter | null | undefined;
};

export type TestimonialFilter = {
  quote?: StringFilter | null | undefined;
  author?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  organization?: StringFilter | null | undefined;
  event?: StringFilter | null | undefined;
  avatarText?: StringFilter | null | undefined;
};

export type ShowreelVideoFilter = {
  title?: StringFilter | null | undefined;
  caption?: StringFilter | null | undefined;
  thumb?: StringFilter | null | undefined;
  videoUrl?: StringFilter | null | undefined;
};

export type FaqFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
};

export type PersonalInfoPartsFragment = { __typename: 'PersonalInfo', name: string | null, title: string | null, subtitle: string | null, heroHeadline: string | null, tagline: string | null, portrait: string | null, showreelUrl: string | null, experienceYears: number | null, eventsCount: number | null, broadcastersCount: number | null, uptimePercentage: string | null, location: string | null, phone: string | null, email: string | null, whatsappUrl: string | null, workingHours: string | null, degree: string | null, degreeHonors: string | null, statusText: string | null, statusTextShort: string | null, statusActive: boolean | null, socials: Array<{ __typename: 'PersonalInfoSocials', label: string | null, url: string | null } | null> | null };

export type EventPartsFragment = { __typename: 'Event', slug: string, title: string | null, subtitle: string | null, category: string | null, venue: string | null, broadcaster: string | null, dates: string | null, role: string | null, heroImage: string | null, gallery: Array<string | null> | null, videoUrl: string | null, summary: string | null, cameraCount: number | null, technicalApproach: Array<string | null> | null, outcomes: Array<string | null> | null, improvementReflection: string | null, tags: Array<string | null> | null, specs: { __typename: 'EventSpecs', format: string | null, visionMixer: string | null, replay: string | null, cameras: string | null, syncRouter: string | null, audioIntercom: string | null } | null, keyStats: Array<{ __typename: 'EventKeyStats', label: string | null, value: string | null } | null> | null, signalFlow: Array<{ __typename: 'EventSignalFlow', step: string | null, description: string | null } | null> | null, challengesAndSolutions: Array<{ __typename: 'EventChallengesAndSolutions', challenge: string | null, solution: string | null, impact: string | null } | null> | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, description: string | null };

export type EquipmentPartsFragment = { __typename: 'Equipment', name: string, iconName: string | null, description: string | null, items: Array<{ __typename: 'EquipmentItems', name: string | null, model: string | null, manufacturer: string | null, role: string | null, protocols: Array<string | null> | null, experienceYears: number | null, featured: boolean | null } | null> | null };

export type TimelinePartsFragment = { __typename: 'Timeline', period: string, role: string | null, company: string | null, location: string | null, type: string | null, description: string | null, achievements: Array<string | null> | null, technologies: Array<string | null> | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', quote: string, author: string | null, role: string | null, organization: string | null, event: string | null, avatarText: string | null };

export type ShowreelVideoPartsFragment = { __typename: 'ShowreelVideo', title: string, caption: string | null, thumb: string | null, videoUrl: string | null };

export type FaqPartsFragment = { __typename: 'Faq', question: string, answer: string | null };

export type PersonalInfoQueryVariables = Exact<{
  relativePath: string;
}>;


export type PersonalInfoQuery = { personalInfo: { __typename: 'PersonalInfo', id: string, name: string | null, title: string | null, subtitle: string | null, heroHeadline: string | null, tagline: string | null, portrait: string | null, showreelUrl: string | null, experienceYears: number | null, eventsCount: number | null, broadcastersCount: number | null, uptimePercentage: string | null, location: string | null, phone: string | null, email: string | null, whatsappUrl: string | null, workingHours: string | null, degree: string | null, degreeHonors: string | null, statusText: string | null, statusTextShort: string | null, statusActive: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials: Array<{ __typename: 'PersonalInfoSocials', label: string | null, url: string | null } | null> | null } };

export type PersonalInfoConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PersonalInfoFilter | null | undefined;
}>;


export type PersonalInfoConnectionQuery = { personalInfoConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'PersonalInfo', id: string, name: string | null, title: string | null, subtitle: string | null, heroHeadline: string | null, tagline: string | null, portrait: string | null, showreelUrl: string | null, experienceYears: number | null, eventsCount: number | null, broadcastersCount: number | null, uptimePercentage: string | null, location: string | null, phone: string | null, email: string | null, whatsappUrl: string | null, workingHours: string | null, degree: string | null, degreeHonors: string | null, statusText: string | null, statusTextShort: string | null, statusActive: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials: Array<{ __typename: 'PersonalInfoSocials', label: string | null, url: string | null } | null> | null } | null } | null> | null } };

export type EventQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventQuery = { event: { __typename: 'Event', id: string, slug: string, title: string | null, subtitle: string | null, category: string | null, venue: string | null, broadcaster: string | null, dates: string | null, role: string | null, heroImage: string | null, gallery: Array<string | null> | null, videoUrl: string | null, summary: string | null, cameraCount: number | null, technicalApproach: Array<string | null> | null, outcomes: Array<string | null> | null, improvementReflection: string | null, tags: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, specs: { __typename: 'EventSpecs', format: string | null, visionMixer: string | null, replay: string | null, cameras: string | null, syncRouter: string | null, audioIntercom: string | null } | null, keyStats: Array<{ __typename: 'EventKeyStats', label: string | null, value: string | null } | null> | null, signalFlow: Array<{ __typename: 'EventSignalFlow', step: string | null, description: string | null } | null> | null, challengesAndSolutions: Array<{ __typename: 'EventChallengesAndSolutions', challenge: string | null, solution: string | null, impact: string | null } | null> | null } };

export type EventConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventFilter | null | undefined;
}>;


export type EventConnectionQuery = { eventConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Event', id: string, slug: string, title: string | null, subtitle: string | null, category: string | null, venue: string | null, broadcaster: string | null, dates: string | null, role: string | null, heroImage: string | null, gallery: Array<string | null> | null, videoUrl: string | null, summary: string | null, cameraCount: number | null, technicalApproach: Array<string | null> | null, outcomes: Array<string | null> | null, improvementReflection: string | null, tags: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, specs: { __typename: 'EventSpecs', format: string | null, visionMixer: string | null, replay: string | null, cameras: string | null, syncRouter: string | null, audioIntercom: string | null } | null, keyStats: Array<{ __typename: 'EventKeyStats', label: string | null, value: string | null } | null> | null, signalFlow: Array<{ __typename: 'EventSignalFlow', step: string | null, description: string | null } | null> | null, challengesAndSolutions: Array<{ __typename: 'EventChallengesAndSolutions', challenge: string | null, solution: string | null, impact: string | null } | null> | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: string;
}>;


export type ServiceQuery = { service: { __typename: 'Service', id: string, title: string, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ServiceFilter | null | undefined;
}>;


export type ServiceConnectionQuery = { serviceConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Service', id: string, title: string, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EquipmentQueryVariables = Exact<{
  relativePath: string;
}>;


export type EquipmentQuery = { equipment: { __typename: 'Equipment', id: string, name: string, iconName: string | null, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items: Array<{ __typename: 'EquipmentItems', name: string | null, model: string | null, manufacturer: string | null, role: string | null, protocols: Array<string | null> | null, experienceYears: number | null, featured: boolean | null } | null> | null } };

export type EquipmentConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EquipmentFilter | null | undefined;
}>;


export type EquipmentConnectionQuery = { equipmentConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Equipment', id: string, name: string, iconName: string | null, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items: Array<{ __typename: 'EquipmentItems', name: string | null, model: string | null, manufacturer: string | null, role: string | null, protocols: Array<string | null> | null, experienceYears: number | null, featured: boolean | null } | null> | null } | null } | null> | null } };

export type TimelineQueryVariables = Exact<{
  relativePath: string;
}>;


export type TimelineQuery = { timeline: { __typename: 'Timeline', id: string, period: string, role: string | null, company: string | null, location: string | null, type: string | null, description: string | null, achievements: Array<string | null> | null, technologies: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TimelineConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TimelineFilter | null | undefined;
}>;


export type TimelineConnectionQuery = { timelineConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Timeline', id: string, period: string, role: string | null, company: string | null, location: string | null, type: string | null, description: string | null, achievements: Array<string | null> | null, technologies: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: string;
}>;


export type TestimonialQuery = { testimonial: { __typename: 'Testimonial', id: string, quote: string, author: string | null, role: string | null, organization: string | null, event: string | null, avatarText: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TestimonialFilter | null | undefined;
}>;


export type TestimonialConnectionQuery = { testimonialConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Testimonial', id: string, quote: string, author: string | null, role: string | null, organization: string | null, event: string | null, avatarText: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ShowreelVideoQueryVariables = Exact<{
  relativePath: string;
}>;


export type ShowreelVideoQuery = { showreelVideo: { __typename: 'ShowreelVideo', id: string, title: string, caption: string | null, thumb: string | null, videoUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ShowreelVideoConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ShowreelVideoFilter | null | undefined;
}>;


export type ShowreelVideoConnectionQuery = { showreelVideoConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'ShowreelVideo', id: string, title: string, caption: string | null, thumb: string | null, videoUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: string;
}>;


export type FaqQuery = { faq: { __typename: 'Faq', id: string, question: string, answer: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FaqConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FaqFilter | null | undefined;
}>;


export type FaqConnectionQuery = { faqConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Faq', id: string, question: string, answer: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PersonalInfoPartsFragmentDoc = gql`
    fragment PersonalInfoParts on PersonalInfo {
  __typename
  name
  title
  subtitle
  heroHeadline
  tagline
  portrait
  showreelUrl
  experienceYears
  eventsCount
  broadcastersCount
  uptimePercentage
  location
  phone
  email
  whatsappUrl
  workingHours
  socials {
    __typename
    label
    url
  }
  degree
  degreeHonors
  statusText
  statusTextShort
  statusActive
}
    `;
export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  slug
  title
  subtitle
  category
  venue
  broadcaster
  dates
  role
  heroImage
  gallery
  videoUrl
  summary
  cameraCount
  specs {
    __typename
    format
    visionMixer
    replay
    cameras
    syncRouter
    audioIntercom
  }
  keyStats {
    __typename
    label
    value
  }
  technicalApproach
  signalFlow {
    __typename
    step
    description
  }
  challengesAndSolutions {
    __typename
    challenge
    solution
    impact
  }
  outcomes
  improvementReflection
  tags
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  description
}
    `;
export const EquipmentPartsFragmentDoc = gql`
    fragment EquipmentParts on Equipment {
  __typename
  name
  iconName
  description
  items {
    __typename
    name
    model
    manufacturer
    role
    protocols
    experienceYears
    featured
  }
}
    `;
export const TimelinePartsFragmentDoc = gql`
    fragment TimelineParts on Timeline {
  __typename
  period
  role
  company
  location
  type
  description
  achievements
  technologies
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  quote
  author
  role
  organization
  event
  avatarText
}
    `;
export const ShowreelVideoPartsFragmentDoc = gql`
    fragment ShowreelVideoParts on ShowreelVideo {
  __typename
  title
  caption
  thumb
  videoUrl
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  question
  answer
}
    `;
export const PersonalInfoDocument = gql`
    query personalInfo($relativePath: String!) {
  personalInfo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PersonalInfoParts
  }
}
    ${PersonalInfoPartsFragmentDoc}`;
export const PersonalInfoConnectionDocument = gql`
    query personalInfoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PersonalInfoFilter) {
  personalInfoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PersonalInfoParts
      }
    }
  }
}
    ${PersonalInfoPartsFragmentDoc}`;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const EquipmentDocument = gql`
    query equipment($relativePath: String!) {
  equipment(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EquipmentParts
  }
}
    ${EquipmentPartsFragmentDoc}`;
export const EquipmentConnectionDocument = gql`
    query equipmentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EquipmentFilter) {
  equipmentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EquipmentParts
      }
    }
  }
}
    ${EquipmentPartsFragmentDoc}`;
export const TimelineDocument = gql`
    query timeline($relativePath: String!) {
  timeline(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TimelineParts
  }
}
    ${TimelinePartsFragmentDoc}`;
export const TimelineConnectionDocument = gql`
    query timelineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TimelineFilter) {
  timelineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TimelineParts
      }
    }
  }
}
    ${TimelinePartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const ShowreelVideoDocument = gql`
    query showreelVideo($relativePath: String!) {
  showreelVideo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShowreelVideoParts
  }
}
    ${ShowreelVideoPartsFragmentDoc}`;
export const ShowreelVideoConnectionDocument = gql`
    query showreelVideoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShowreelVideoFilter) {
  showreelVideoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShowreelVideoParts
      }
    }
  }
}
    ${ShowreelVideoPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      personalInfo(variables: PersonalInfoQueryVariables, options?: C): Promise<{data: PersonalInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonalInfoQueryVariables, query: string}> {
        return requester<{data: PersonalInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonalInfoQueryVariables, query: string}, PersonalInfoQueryVariables>(PersonalInfoDocument, variables, options);
      },
    personalInfoConnection(variables?: PersonalInfoConnectionQueryVariables, options?: C): Promise<{data: PersonalInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonalInfoConnectionQueryVariables, query: string}> {
        return requester<{data: PersonalInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonalInfoConnectionQueryVariables, query: string}, PersonalInfoConnectionQueryVariables>(PersonalInfoConnectionDocument, variables, options);
      },
    event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    equipment(variables: EquipmentQueryVariables, options?: C): Promise<{data: EquipmentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentQueryVariables, query: string}> {
        return requester<{data: EquipmentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentQueryVariables, query: string}, EquipmentQueryVariables>(EquipmentDocument, variables, options);
      },
    equipmentConnection(variables?: EquipmentConnectionQueryVariables, options?: C): Promise<{data: EquipmentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentConnectionQueryVariables, query: string}> {
        return requester<{data: EquipmentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentConnectionQueryVariables, query: string}, EquipmentConnectionQueryVariables>(EquipmentConnectionDocument, variables, options);
      },
    timeline(variables: TimelineQueryVariables, options?: C): Promise<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}> {
        return requester<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}, TimelineQueryVariables>(TimelineDocument, variables, options);
      },
    timelineConnection(variables?: TimelineConnectionQueryVariables, options?: C): Promise<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}> {
        return requester<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}, TimelineConnectionQueryVariables>(TimelineConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    showreelVideo(variables: ShowreelVideoQueryVariables, options?: C): Promise<{data: ShowreelVideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowreelVideoQueryVariables, query: string}> {
        return requester<{data: ShowreelVideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowreelVideoQueryVariables, query: string}, ShowreelVideoQueryVariables>(ShowreelVideoDocument, variables, options);
      },
    showreelVideoConnection(variables?: ShowreelVideoConnectionQueryVariables, options?: C): Promise<{data: ShowreelVideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowreelVideoConnectionQueryVariables, query: string}> {
        return requester<{data: ShowreelVideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowreelVideoConnectionQueryVariables, query: string}, ShowreelVideoConnectionQueryVariables>(ShowreelVideoConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/b4832c73-1d3e-4aad-9f22-17177ecc3782/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  