// AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
// Run `npm run codegen` to regenerate from content/ files.

import type {
  PersonalInfo,
  CaseStudy,
  ServiceTier,
  EquipmentCategory,
  TimelineNode,
  Testimonial,
  ShowcaseVideo,
  FaqItem,
} from "./types";

export const PERSONAL_INFO: PersonalInfo = {
  "name": "Samir Elgammal",
  "title": "System Broadcast & OB Engineer",
  "subtitle": "CCU & EVS Replay Specialist",
  "heroHeadline": "Video production that brings your story into focus",
  "tagline": "System Broadcast and OB Engineer with more than 18 years of experience in OBs, broadcasting studios, playout engineering, CCU operator and EVS operator and guarantee. Specialized in sports studios with strong problem-solving skills and a creative approach to designing and implementing studio schematics and playout centers.",
  "portrait": "/images/samir-portrait.jpg",
  "showreelUrl": "https://www.youtube.com/watch?v=-UM3atf8iAI",
  "experienceYears": 18,
  "eventsCount": 150,
  "broadcastersCount": 22,
  "uptimePercentage": "99.99%",
  "location": "Dubai, United Arab Emirates",
  "phone": "+971 50 563 9015",
  "email": "s.elgammal12@gmail.com",
  "whatsappUrl": "https://wa.me/971505639015?text=Hello%20Samir,%20I%20would%20like%20to%20inquire%20about%20your%20broadcast%20engineering%20services.",
  "workingHours": "Sat – Thu · 09:00 – 18:00 (GST)",
  "socials": [
    {
      "label": "Facebook",
      "url": ""
    },
    {
      "label": "X (Twitter)",
      "url": ""
    }
  ],
  "degree": "Bachelor of Electrical Engineering – Communication & Electronics",
  "degreeHonors": "Very Good with Honors (B.Sc. Eng)",
  "statusText": "AVAILABLE FOR UAE, GCC & INTERNATIONAL FLYAWAY",
  "statusTextShort": "UAE, GCC & FLYAWAY",
  "statusActive": true
};

export const FLAGSHIP_EVENTS: CaseStudy[] = [
  {
    "slug": "abu-dhabi-jiu-jitsu-world-championship",
    "heroImage": "/images/events/jitsi-cover.jpg",
    "gallery": [
      "/images/events/g-tech.jpg",
      "/images/events/g-pitch.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=558JWScMdcY",
    "title": "Abu Dhabi Jiu-Jitsu World Championship",
    "subtitle": "8-Mat Simultaneous Live Feeds & Instant Referee Video Review",
    "category": "Combat Sports",
    "venue": "ARENA Space42, Zayed Sports City, Abu Dhabi",
    "broadcaster": "Abu Dhabi Sports & International Combat Streams",
    "dates": "Annual Championship 2022 – 2025",
    "role": "Senior Broadcast Engineer & Multi-Feed Matrix Lead",
    "summary": "Engineered an 8-mat simultaneous broadcast infrastructure delivering 8 discrete live stadium video feeds, centralized referee review video replay, and main arena show court broadcast coverage.",
    "cameraCount": 24,
    "specs": {
      "format": "1080p50 HD-SDI Matrix",
      "visionMixer": "Sony MVS-7000X + FOR-A HVS-390HS Sub-Mixers",
      "replay": "3x EVS XT3 (18 Channels Synchronized)",
      "cameras": "Sony HDC-3500 + Jib Crane + Wireless Steadicams",
      "syncRouter": "Nevion Sublime 128x128 Routing Matrix",
      "audioIntercom": "RTS ADAM Intercom + Dante AoIP Network"
    },
    "keyStats": [
      {
        "label": "Mats Broadcast Simultaneously",
        "value": "8 Mats"
      },
      {
        "label": "Total Bouts Covered",
        "value": "1,200+"
      },
      {
        "label": "Referee Review Requests",
        "value": "450+"
      },
      {
        "label": "Live Stream Channels",
        "value": "10 Feeds"
      }
    ],
    "technicalApproach": [
      "Engineered a centralized 128x128 Nevion matrix routing all 8 competition mats to dedicated referee touchscreens and online feeds.",
      "Configured 3 synchronized EVS XT3 servers to log and instantly cue contentious point scoring and submission attempts.",
      "Managed RF Steadicam and 40ft Jimmy Jib cameras for the grand championship final show court."
    ],
    "signalFlow": [
      {
        "step": "Multi-Mat Ingest",
        "description": "24 camera lines across 8 mats routed to central OB patch panel"
      },
      {
        "step": "Referee Review Station",
        "description": "Instant touch-controlled replay distribution to mat-side referees"
      },
      {
        "step": "Main Court Production",
        "description": "Sony MVS-7000X directing prime-time finals broadcast with slow-motion replays"
      },
      {
        "step": "Graphics & Scoring",
        "description": "WTvision live tournament bracket and scoring integration"
      },
      {
        "step": "OTT & TV Distribution",
        "description": "10 discrete streams encoded for global streaming portals and Abu Dhabi Sports TV"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "Mat 4 and Mat 7 had simultaneous contested gold-medal submissions requiring immediate video replay.",
        "solution": "Dual-operator EVS workflow routing isolated angles to separate referee review monitors simultaneously.",
        "impact": "Both decisions resolved in under 15 seconds; broadcast pace was maintained without delay."
      }
    ],
    "outcomes": [
      "Successfully streamed 8 simultaneous courts for 7 consecutive days with zero signal interruptions.",
      "Earned official commendation from UAE Jiu-Jitsu Federation."
    ],
    "improvementReflection": "Deploying automated AI clip-tagging for athlete names will accelerate social media highlight turnaround.",
    "tags": [
      "Jiu-Jitsu",
      "Space42 Arena",
      "Multi-Mat",
      "EVS XT3",
      "Nevion Matrix",
      "Combat Sports"
    ]
  },
  {
    "slug": "camel-racing-heritage-festivals",
    "heroImage": "/images/events/desert-cover.jpg",
    "gallery": [
      "/images/events/g-sand.jpg",
      "/images/events/g-studio.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=558JWScMdcY",
    "title": "National Camel & Desert Racing Championships",
    "subtitle": "Extreme Desert Environment RF Wireless & High-Speed Mobile OB",
    "category": "Heritage",
    "venue": "Al Dhafra Festival, Al Wathbah, Muzayna, Al Labsah",
    "broadcaster": "YAS TV / Abu Dhabi Media",
    "dates": "2019 – 2026 Annual Seasons",
    "role": "Senior OB Engineer & RF Wireless Signal Specialist",
    "summary": "Pioneered specialized mobile OB operations in extreme desert conditions (45°C heat, fine sandstorms) with high-speed tracking vehicles, long-range Vislink RF camera links, and dynamic desert sun shading.",
    "cameraCount": 22,
    "specs": {
      "format": "1080i50 / 1080p50 Broadcast Standard",
      "visionMixer": "FOR-A HVS-2000 & Sony MVS-6530",
      "replay": "EVS XT3 Max (8 Channel) with Multicam LSM",
      "cameras": "Sony HDC-3500 + Grass Valley LDX 86N + Gyro-Stabilized Tracking Cams",
      "syncRouter": "Vislink Wireless RF Receivers + Nevion 64x64 SDI",
      "audioIntercom": "Midas Pro 2 Digital Audio + RTS Telex Intercom"
    },
    "keyStats": [
      {
        "label": "Track Length Covered",
        "value": "10 km"
      },
      {
        "label": "RF Range Maintained",
        "value": "12 km"
      },
      {
        "label": "Ambient Temp Max",
        "value": "48°C"
      },
      {
        "label": "Live Race Transmissions",
        "value": "240+"
      }
    ],
    "technicalApproach": [
      "Engineered multi-node RF diversity antenna arrays across 8km–10km desert tracks with automated antenna switching.",
      "Customized positive-pressure dust filtration and secondary cooling for OB truck server racks during desert sand conditions.",
      "Maintained extreme dynamic range CCU shading between golden desert sand dunes and high-intensity Arabian midday sun."
    ],
    "signalFlow": [
      {
        "step": "Mobile Tracking Cams",
        "description": "Gyro-stabilized cameras on 4x4 chase vehicles transmitting over Vislink RF"
      },
      {
        "step": "RF Diversity Towers",
        "description": "Triple antenna receiver masts along 10km race perimeter"
      },
      {
        "step": "Baseband Demodulation",
        "description": "COFDM receivers demodulating RF signals directly into OB router"
      },
      {
        "step": "Fast-Paced EVS Clipping",
        "description": "LSM operators logging lead camel split times and photo-finish angles"
      },
      {
        "step": "Master Transmission",
        "description": "Microwave link direct to YAS TV teleport station"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "Extreme desert heat causing RF transmitter thermal throttling on lead tracking vehicle during 10km race.",
        "solution": "Installed custom aluminum heatsink ducted fans with quick-swap cold gel packs between race heats.",
        "impact": "Maintained 100% RF signal power output with zero frame drops throughout all heats."
      },
      {
        "challenge": "Intense sand glare blowing out camera dynamic range on standard gamma curves.",
        "solution": "Engineered a custom S-Log/HyperGamma knee curve preset on Sony RCP-1500 paint boxes, protecting sky and sand highlights.",
        "impact": "Rich, broadcast-award-winning visual color fidelity praised by YAS TV production team."
      }
    ],
    "outcomes": [
      "Over 240 live desert races broadcast without a single dropped race finish or signal dropout.",
      "Recognized by Media Mania as the premier RF & OB engineering lead for Gulf heritage sports."
    ],
    "improvementReflection": "Implementing automated GPS-steered tracking antennas on receiver towers would further enhance signal margin on extreme 12km marathons.",
    "tags": [
      "Camel Racing",
      "Al Dhafra",
      "Vislink RF",
      "Desert OB",
      "FOR-A HVS-2000",
      "Gyro-Cam"
    ]
  },
  {
    "slug": "cop28-expo-city-dubai",
    "heroImage": "/images/events/cop28-cover.jpg",
    "gallery": [
      "/images/events/g-camera.jpg",
      "/images/events/g-mic.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=-UM3atf8iAI",
    "title": "COP28 UN Climate Summit",
    "subtitle": "Global Unilateral & Host Broadcaster Transmission Matrix",
    "category": "Summit",
    "venue": "Expo City Dubai, UAE",
    "broadcaster": "Abu Dhabi TV / UNFCCC Host Broadcast",
    "dates": "Nov 30 – Dec 13, 2023",
    "role": "Lead OB Systems Engineer & Signal Routing Lead",
    "summary": "Engineered zero-latency international distribution matrix across 35+ multilateral feeds, high-security presidential plenary halls, and global network unilateral cabins with 100% transmission continuity.",
    "cameraCount": 28,
    "specs": {
      "format": "1080p50 HDR / 12G-SDI & SMPTE 2110 Hybrid",
      "visionMixer": "Sony MVS-8000X (4 M/E Main Plenary + 2 M/E Side Halls)",
      "replay": "EVS XT-VIA & XT3 (8 Channel Speech Loggers)",
      "cameras": "18x Sony HDC-4300 + 10x Remote Robotic PTZs",
      "syncRouter": "Evertz 5600SPG Dual Redundant Master Sync + Nevion Sublime 128x128",
      "audioIntercom": "RTS ADAM Matrix (128 Ports) + Dante Network Bridges"
    },
    "keyStats": [
      {
        "label": "Global Audience",
        "value": "1.2B+"
      },
      {
        "label": "Unilateral Feeds",
        "value": "35+"
      },
      {
        "label": "Continuous On-Air",
        "value": "312 Hrs"
      },
      {
        "label": "Signal Loss Incidents",
        "value": "0"
      }
    ],
    "technicalApproach": [
      "Designed a dual-ring fiber backbone connecting the Plenary Hall OB Compound to International Media Centre (IMC) distribution hubs.",
      "Configured redundant Evertz SPG synchronizers with GPS locking to guarantee jitter-free reference across 28 multi-vendor camera channels.",
      "Established strict CCU colorimetry matching calibrated for low-glare presidential lighting and 4K HDR projection backdrops."
    ],
    "signalFlow": [
      {
        "step": "Optical Ingest",
        "description": "28 SMPTE hybrid fiber camera runs terminated at tactical patch-wall"
      },
      {
        "step": "CCU Paint Box",
        "description": "Sony RCP-1500 master rack aligned to D65 color temp"
      },
      {
        "step": "Matrix Routing",
        "description": "Nevion 128x128 HD-SDI router with automated fallback switching"
      },
      {
        "step": "Vision Mixing",
        "description": "Sony MVS-8000X delivering 4 distinct international clean & graphic feeds"
      },
      {
        "step": "Satellite Uplink & Fiber Tx",
        "description": "Dual redundant encoders routed to EBU and Abu Dhabi Media playout"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "Unannounced VIP arrival caused spontaneous room reassignment 20 minutes before world leaders address.",
        "solution": "Triggered emergency flyaway optical multiplexer preset, re-patching 6 CCU channels and RTS intercom panels over dark fiber trunk in 8 minutes.",
        "impact": "Zero transmission delay; world feed went live flawlessly with synchronized tally and graphics."
      },
      {
        "challenge": "Severe thermal fluctuations in external outdoor fiber termination hubs reaching 42°C ambient.",
        "solution": "Implemented active thermoelectric spot cooling and optical power margin monitoring on all tactical SMPTE cables.",
        "impact": "Prevented optical dB attenuation drops throughout the 14-day summit."
      }
    ],
    "outcomes": [
      "Delivered flawless 24/7 world feed to 140+ accredited international television networks.",
      "Commended by Abu Dhabi Media engineering directorate for exemplary uptime and rapid emergency re-patching."
    ],
    "improvementReflection": "In future mega-summits, I would deploy automated SMPTE ST 2110 NMOS IS-04/05 discovery for unilateral client trucks to cut initial patching times by another 40%.",
    "tags": [
      "COP28",
      "World Feed",
      "Sony MVS-8000X",
      "Evertz SPG",
      "RTS ADAM",
      "SMPTE Fiber"
    ]
  },
  {
    "slug": "primetime-game-shows-emirates-draw",
    "heroImage": "/images/events/draw-cover.jpg",
    "gallery": [
      "/images/events/g-filming.jpg",
      "/images/events/g-engineer.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=GzxZcTk2HT4",
    "title": "Emirates Draw & Primetime Live Shows",
    "subtitle": "High-Security RNG Verification & Redundant Pebble Beach Playout",
    "category": "Entertainment",
    "venue": "Media City & MAP Studio Facilities, Dubai",
    "broadcaster": "Emirates Draw / Dubai TV / Digital Streams",
    "dates": "2021 – 2026 Weekly Live Broadcasts",
    "role": "Lead Playout & Studio Systems Engineer",
    "summary": "Managed high-stakes, multi-million dollar live lottery draws, game shows, and weekly primetime entertainment (Emirates Draw, Little Draw, Esaad Police, Top Chef ME) with strict regulatory compliance and dual-redundant automation.",
    "cameraCount": 12,
    "specs": {
      "format": "1080p50 Full HD SDI",
      "visionMixer": "Sony DVS-9000 & FOR-A HVS-2000",
      "replay": "EVS XT3 & Harris Inscriber Servers",
      "cameras": "Sony HDC-3500 & Sony BRC-X1000 4K PTZ",
      "syncRouter": "Pebble Beach Marina Automation + Evertz SPG",
      "audioIntercom": "Yamaha CL5 Console + RTS Intercom"
    },
    "keyStats": [
      {
        "label": "Live Weekly Draws",
        "value": "180+"
      },
      {
        "label": "Prize Pools Guaranteed",
        "value": "$100M+"
      },
      {
        "label": "Playout Redundancy",
        "value": "Dual Hot-Standby"
      },
      {
        "label": "Regulatory Compliance",
        "value": "100%"
      }
    ],
    "technicalApproach": [
      "Configured Pebble Beach Marina automation for synchronized primary and secondary failover playout channels.",
      "Synchronized 8 multi-angle high-speed ball machine cameras with millisecond timecode burn-in for regulatory auditing.",
      "Integrated real-time graphics automation (Brainstorm & Vizrt) pulling verified numbers directly from air-gapped audit servers."
    ],
    "signalFlow": [
      {
        "step": "Ball Machine Ingest",
        "description": "4K high-speed cameras locked onto pneumatic lottery draw chambers"
      },
      {
        "step": "Audit Verification",
        "description": "Timecode burned splits routed simultaneously to government audit monitors"
      },
      {
        "step": "Live Graphics Trigger",
        "description": "Brainstorm eStudio CG rendering live winning numbers in real-time"
      },
      {
        "step": "Playout Automation",
        "description": "Pebble Beach Marina firing synchronized primary and backup transmission lines"
      },
      {
        "step": "Multi-Platform Streaming",
        "description": "Simultaneous TV broadcast and ultra-low-latency YouTube/Facebook live streams"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "Primary graphics workstation experienced a GPU frame-buffer lock 90 seconds before live countdown.",
        "solution": "Seamlessly toggled the video router clean-switch to the secondary mirrored Brainstorm engine without a dropped pixel.",
        "impact": "Broadcast started precisely on schedule with 100% graphics fidelity."
      }
    ],
    "outcomes": [
      "Maintained unbroken 100% on-air compliance across over 180 consecutive live weekly draw episodes.",
      "Awarded Certificate of Technical Excellence by Media Art Production (MAP)."
    ],
    "improvementReflection": "Transitioning to cloud-synchronized SRT backup streams further bolstered international streaming resilience.",
    "tags": [
      "Emirates Draw",
      "Pebble Beach",
      "Brainstorm CG",
      "Studio Playout",
      "Sony DVS-9000",
      "Top Chef"
    ]
  },
  {
    "slug": "uae-pro-league-adnoc",
    "heroImage": "/images/events/pro-league-cover.jpg",
    "gallery": [
      "/images/events/g-pitch.jpg",
      "/images/events/g-tech.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=GzxZcTk2HT4",
    "title": "UAE Pro League (ADNOC Football)",
    "subtitle": "16-Camera 4K Live OB Truck & Dual EVS Super Slow-Mo",
    "category": "Sports",
    "venue": "Zayed Sports City & Hazza Bin Zayed Stadiums",
    "broadcaster": "Abu Dhabi Sports & Dubai Sports",
    "dates": "2021 – 2026 Regular Season",
    "role": "OB System Engineer, CCU Operator & EVS Replay Lead",
    "summary": "Full end-to-end technical engineering for tier-1 live professional football matches, overseeing 16-camera setups, high-frame-rate super slow-mo, VAR integration, and dynamic floodlight camera matching.",
    "cameraCount": 16,
    "specs": {
      "format": "1080p50 High Dynamic Range (HLG)",
      "visionMixer": "Sony MVS-7000X (3 M/E Production Switcher)",
      "replay": "2x EVS XT3 Max (12 Channels Total) + LSM Remote Panels",
      "cameras": "12x Sony HDC-3500 + 4x HDC-4300 (3x/6x Super Slow-Motion)",
      "syncRouter": "Nevion Sublime 64x64 + Evertz 7700 Frame Sync",
      "audioIntercom": "Studer Vista 5 Digital Console + Trilogy Intercom Matrix"
    },
    "keyStats": [
      {
        "label": "Matches Engineered",
        "value": "85+"
      },
      {
        "label": "Super Slow-Mo Replays",
        "value": "6,000+"
      },
      {
        "label": "VAR Turnaround Delay",
        "value": "< 2.5s"
      },
      {
        "label": "Broadcast Uptime",
        "value": "100%"
      }
    ],
    "technicalApproach": [
      "Rigged and verified 16 camera positions including High-Center, 18-Yard boxes, Reverse Pitch, Steadicam RF, and Super Slow-Mo goal lines.",
      "Calibrated CCU iris and color temperature across shifting natural sunset to stadium halogen/LED floodlights in real-time.",
      "Configured multi-angle EVS clip playlists for instant referee VAR video review and rapid halftime highlight reels."
    ],
    "signalFlow": [
      {
        "step": "Stadium Rigging",
        "description": "Tactile fiber triax runs across gantry, pitch-level, and reverse towers"
      },
      {
        "step": "CCU Live Shading",
        "description": "Real-time master black and knee tracking on Sony RCP-1500 panels"
      },
      {
        "step": "EVS Ingest & Replay",
        "description": "Synchronized multi-angle recording on dual EVS XT3 Max with LSM controllers"
      },
      {
        "step": "VAR Feed Distribution",
        "description": "Dedicated zero-latency multi-split feed sent directly to VAR referee booth"
      },
      {
        "step": "Program Transmission",
        "description": "Clean and dirty PGM feeds routed to satellite uplink SNG trucks"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "A primary high-speed fiber connection to Camera 3 (Main Reverse) was severed by a stadium grounds vehicle 35 minutes before kickoff.",
        "solution": "Rapidly switched to pre-laid dark fiber backup core and deployed a tactical SMPTE optical conversion jumper within 12 minutes.",
        "impact": "Camera 3 was fully tested, color-matched, and on-air 20 minutes before broadcast countdown."
      },
      {
        "challenge": "Sudden heavy arena floodlight flicker caused rolling banding artifacts on 6x high-speed super slow-mo channels.",
        "solution": "Adjusted electronic shutter angle phase lock on Sony HDC-4300 CCUs to match the 50Hz LED PWM driver cycle.",
        "impact": "Crystal-clear, flicker-free ultra slow-motion replays throughout the match."
      }
    ],
    "outcomes": [
      "Consistently achieved broadcast perfection ratings from Abu Dhabi Sports technical audit board.",
      "Zero missed goals, fouls, or pivotal VAR referee replay demands across entire championship seasons."
    ],
    "improvementReflection": "Transitioning all stadium return video monitors to ultra-low-latency NDI/IP feeds helped directors cue replays 1.2 seconds faster.",
    "tags": [
      "Football",
      "UAE Pro League",
      "EVS XT3 Max",
      "Sony HDC-4300",
      "VAR",
      "Super Slow-Mo"
    ]
  },
  {
    "slug": "world-snooker-masters-ksa",
    "heroImage": "/images/events/snooker-cover.jpg",
    "gallery": [
      "/images/events/g-audio.jpg",
      "/images/events/g-director.jpg"
    ],
    "videoUrl": "https://www.youtube.com/watch?v=JXMvxICIj4w",
    "title": "World Snooker Masters & Riyadh Season",
    "subtitle": "Micro-Detail Lighting Calibration & Ultra-Silent Control",
    "category": "Sports",
    "venue": "Boulevard Riyadh City, Kingdom of Saudi Arabia",
    "broadcaster": "Matchroom Sport / Saudi Sports Company (SSC) / Eurosport",
    "dates": "March 2024",
    "role": "Lead CCU Engineer & System QC Supervisor",
    "summary": "Flawless colorimetry calibration for the high-prestige World Snooker tournament. Demanded zero acoustic noise in arena, ultra-precise baize green color matching, and macro slow-motion ball spin analysis.",
    "cameraCount": 14,
    "specs": {
      "format": "1080p50 UHD/HDR Ready",
      "visionMixer": "Sony MVS-8000X",
      "replay": "EVS XT3 Max with SuperMotion License",
      "cameras": "Grass Valley LDX 86N + Sony HDC-4300 Macro Overhead",
      "syncRouter": "Evertz 5600SPG + Grass Valley NV9000 Router",
      "audioIntercom": "RTS ADAM-M Matrix + Soundcraft Vi3000"
    },
    "keyStats": [
      {
        "label": "Color Match Precision",
        "value": "ΔE < 0.8"
      },
      {
        "label": "Macro Replay FPS",
        "value": "300 fps"
      },
      {
        "label": "Noise Level in Hall",
        "value": "< 25 dB"
      },
      {
        "label": "Live Matches Delivered",
        "value": "32"
      }
    ],
    "technicalApproach": [
      "Calibrated green baize cloth color balance across all 14 cameras to ensure identical RGB values between tight macro ball shots and wide table views.",
      "Integrated 300fps super slow-motion overhead camera to reveal micro ball collisions and cue contact points.",
      "Engineered ultra-quiet sound isolation and fiber routing to guarantee zero equipment noise reached players."
    ],
    "signalFlow": [
      {
        "step": "Table Macro Cams",
        "description": "Overhead 4K optical zoom focused on cue tip impact point"
      },
      {
        "step": "CCU Shading Suite",
        "description": "Precision Grass Valley OCP-400 paint controllers calibrated against X-Rite ColorChecker"
      },
      {
        "step": "SuperMotion Replay",
        "description": "EVS XT3 server continuous buffer capturing 300fps slow-motion cue strikes"
      },
      {
        "step": "Live Graphics Ingest",
        "description": "Vizrt Trio automated ball telemetry and frame score overlays"
      },
      {
        "step": "Host Feed Handover",
        "description": "Simultaneous international clean feed delivery to Matchroom and SSC"
      }
    ],
    "challengesAndSolutions": [
      {
        "challenge": "Slight hue variance between table spot lights caused the green cloth to appear yellowish on tight pocket cameras.",
        "solution": "Created secondary matrix color presets on Grass Valley OCP panels, selectively shifting yellow-green hue by -4° on pocket cameras.",
        "impact": "Uniform, broadcast-perfect baize green across every single camera angle."
      }
    ],
    "outcomes": [
      "Praised by international host directors for the cleanest snooker visual calibration of the season.",
      "Zero technical interruptions throughout the multi-day championship."
    ],
    "improvementReflection": "Adding automated robotic micro-jib tracks on overhead positions will allow seamless 360-degree table orbits in future tournaments.",
    "tags": [
      "Snooker",
      "Riyadh Season",
      "Grass Valley LDX",
      "Macro CCU",
      "Color Calibration",
      "Matchroom"
    ]
  }
];

export const SERVICE_TIERS: ServiceTier[] = [
  {
    "id": "basic-video-production",
    "title": "Basic video production",
    "description": "A straightforward production option for personal videos, social content, and concise visual stories. Get professional guidance and a refined final edit designed to make your message clear."
  },
  {
    "id": "business-video-production",
    "title": "Business video production",
    "description": "Engaging corporate videos, promotional content, customer stories, and social media assets produced for your brand and audience."
  },
  {
    "id": "enterprise-video-production",
    "title": "Enterprise video production",
    "description": "Plan and deliver larger video initiatives with end-to-end creative support. This flexible option is built for organizations that need consistent, high-quality video at scale."
  },
  {
    "id": "professional-video-production",
    "title": "Professional video production",
    "description": "Elevate your project with a tailored production approach, from creative planning through filming and post-production. Ideal for polished campaigns, profiles, and branded content."
  }
];

export const EQUIPMENT_STACK: EquipmentCategory[] = [
  {
    "id": "audio-intercom",
    "name": "Audio Consoles & Intercom Matrix",
    "iconName": "Volume2",
    "description": "Digital audio mixing desks, matrix talkback, and multi-channel production party-lines.",
    "items": [
      {
        "name": "RTS ADAM & ADAM-M",
        "model": "128-Port Matrix Intercom",
        "manufacturer": "RTS / Bosch",
        "role": "Master Production Intercom",
        "protocols": [
          "OMNEO",
          "RVON VoIP",
          "Keypanel Bus"
        ],
        "experienceYears": 14,
        "featured": true
      },
      {
        "name": "Trilogy Commander",
        "model": "Matrix Communications System",
        "manufacturer": "Clear-Com / Trilogy",
        "role": "OB Truck Talkback System",
        "protocols": [
          "IP",
          "4-Wire Analog"
        ],
        "experienceYears": 12
      },
      {
        "name": "Studer Vista 5",
        "model": "Digital Live Broadcast Console",
        "manufacturer": "Studer / Harman",
        "role": "Live Surround Sports Audio",
        "protocols": [
          "MADI",
          "D21m I/O Frames"
        ],
        "experienceYears": 10,
        "featured": true
      },
      {
        "name": "Midas Pro 2 / Pro X",
        "model": "Digital Live Mixing Desk",
        "manufacturer": "Midas",
        "role": "Live Event & Studio Audio",
        "protocols": [
          "AES50",
          "Dante AoIP"
        ],
        "experienceYears": 11
      }
    ]
  },
  {
    "id": "automation-playout",
    "name": "Automation & Playout Systems",
    "iconName": "Cpu",
    "description": "Master control room automation, transmission schedulers, and software-defined playout.",
    "items": [
      {
        "name": "Pebble Beach Marina",
        "model": "Enterprise Playout Automation",
        "manufacturer": "Pebble Beach Systems",
        "role": "Master Control Channel Playout",
        "protocols": [
          "VDCP",
          "Router Protocol",
          "API"
        ],
        "experienceYears": 11,
        "featured": true
      },
      {
        "name": "Pebble Beach Neptune",
        "model": "Automated Playout Controller",
        "manufacturer": "Pebble Beach Systems",
        "role": "MCR Automation Engine",
        "protocols": [
          "GPI/O",
          "RS-422"
        ],
        "experienceYears": 13,
        "featured": true
      },
      {
        "name": "vMix Pro / HD",
        "model": "Software Live Switcher & Streamer",
        "manufacturer": "StudioCoast",
        "role": "Backup Digital Playout & Web Tx",
        "protocols": [
          "NDI",
          "SRT",
          "RTMP",
          "SDI"
        ],
        "experienceYears": 8
      }
    ]
  },
  {
    "id": "ccu-cameras",
    "name": "Cameras & CCU Paint Boxes",
    "iconName": "Camera",
    "description": "Studio, OB, and high-speed Super Slow-Mo camera channels with master remote paint boxes.",
    "items": [
      {
        "name": "Sony HDC-4300",
        "model": "4K / 8x Super Slow-Motion",
        "manufacturer": "Sony",
        "role": "Tier-1 Live Sports Camera",
        "protocols": [
          "SMPTE Fiber",
          "12G-SDI",
          "Rec.2020"
        ],
        "experienceYears": 9,
        "featured": true
      },
      {
        "name": "Sony HDC-3500",
        "model": "2/3-inch 4K HDR CMOS",
        "manufacturer": "Sony",
        "role": "Primary OB & Studio Camera",
        "protocols": [
          "Global Shutter",
          "HLG",
          "S-Log3"
        ],
        "experienceYears": 7,
        "featured": true
      },
      {
        "name": "Sony RCP-1500 / RCP-3500",
        "model": "Remote Control Panel",
        "manufacturer": "Sony",
        "role": "Master CCU Shading Panel",
        "protocols": [
          "Ethernet",
          "Serial CCA"
        ],
        "experienceYears": 16,
        "featured": true
      },
      {
        "name": "Grass Valley LDX 86N",
        "model": "Native 4K / High-Speed",
        "manufacturer": "Grass Valley",
        "role": "Premium Sports & Studio",
        "protocols": [
          "DirectIP",
          "SMPTE 2110 Ready"
        ],
        "experienceYears": 8,
        "featured": true
      },
      {
        "name": "Grass Valley OCP-400",
        "model": "Operational Control Panel",
        "manufacturer": "Grass Valley",
        "role": "Color & Iris Paint Box",
        "protocols": [
          "C2IP Network"
        ],
        "experienceYears": 11
      },
      {
        "name": "Sony BRC-X1000",
        "model": "4K PTZ Robotic Camera",
        "manufacturer": "Sony",
        "role": "Remote Studio & Plenary",
        "protocols": [
          "VISCA over IP",
          "3G-SDI"
        ],
        "experienceYears": 6
      }
    ]
  },
  {
    "id": "graphics-cg",
    "name": "Graphics, CG & Virtual Sets",
    "iconName": "Monitor",
    "description": "Real-time 3D broadcast character generators, telestration, and virtual studio render engines.",
    "items": [
      {
        "name": "Vizrt Trio & Viz Engine",
        "model": "3D Real-Time Character Generator",
        "manufacturer": "Vizrt",
        "role": "Live Sports & News CG",
        "protocols": [
          "Fill & Key SDI",
          "Shared DB"
        ],
        "experienceYears": 12,
        "featured": true
      },
      {
        "name": "Brainstorm eStudio",
        "model": "Virtual Studio & Augmented Reality",
        "manufacturer": "Brainstorm",
        "role": "Live Primetime Augmented Sets",
        "protocols": [
          "Tracking Protocol",
          "3G-SDI"
        ],
        "experienceYears": 9,
        "featured": true
      },
      {
        "name": "WTvision Studio CG",
        "model": "Sports Graphics & Match Clocks",
        "manufacturer": "WTvision",
        "role": "Tournament Bracket Graphics",
        "protocols": [
          "API Data Ingest",
          "SDI"
        ],
        "experienceYears": 7
      },
      {
        "name": "Piero Sports Graphics",
        "model": "Tactical Broadcast Analysis",
        "manufacturer": "Ross Video",
        "role": "Live Pitch Telestration",
        "protocols": [
          "Multi-Camera Tracking"
        ],
        "experienceYears": 6
      }
    ]
  },
  {
    "id": "replay-servers",
    "name": "Replay & Video Servers",
    "iconName": "Film",
    "description": "Live broadcast replay servers, slow-motion controllers, and ingest storage systems.",
    "items": [
      {
        "name": "EVS XT3 Max",
        "model": "8 / 12 Channel Live Server",
        "manufacturer": "EVS Broadcast",
        "role": "Live Sports Replay & Highlights",
        "protocols": [
          "GigE",
          "SDTI",
          "Dual Multicam"
        ],
        "experienceYears": 15,
        "featured": true
      },
      {
        "name": "EVS XT-VIA",
        "model": "12G-SDI & IP 4K Replay Server",
        "manufacturer": "EVS Broadcast",
        "role": "Ultra-HD Tier-1 Replay",
        "protocols": [
          "SMPTE 2110",
          "12G-SDI"
        ],
        "experienceYears": 5,
        "featured": true
      },
      {
        "name": "EVS LSM Remote",
        "model": "Jog/Shuttle Controller Panel",
        "manufacturer": "EVS Broadcast",
        "role": "Precision Slow-Mo Operation",
        "protocols": [
          "EVS Controller Interface"
        ],
        "experienceYears": 15,
        "featured": true
      },
      {
        "name": "Grass Valley K2 Dyno",
        "model": "Replay System & Summit Server",
        "manufacturer": "Grass Valley",
        "role": "Multi-Channel Clip Server",
        "protocols": [
          "iSCSI",
          "HD-SDI"
        ],
        "experienceYears": 9
      },
      {
        "name": "Harris Inscriber / Nexio",
        "model": "Broadcast Ingest & Server",
        "manufacturer": "Harris / Imagine",
        "role": "Playout Server Storage",
        "protocols": [
          "Fibre Channel",
          "SDI"
        ],
        "experienceYears": 12
      }
    ]
  },
  {
    "id": "routing-sync-rf",
    "name": "Routing, Master Sync & Wireless RF",
    "iconName": "Radio",
    "description": "Baseband routers, GPS-locked SPG generators, and microwave wireless camera links.",
    "items": [
      {
        "name": "Evertz 5600SPG / 5601MSC",
        "model": "Master Sync & Timecode Generator",
        "manufacturer": "Evertz Microsystems",
        "role": "Master Reference Clock & GPS",
        "protocols": [
          "Blackburst",
          "Tri-Level",
          "LTC/VITC"
        ],
        "experienceYears": 15,
        "featured": true
      },
      {
        "name": "Nevion Sublime 128x128",
        "model": "HD/3G-SDI Routing Matrix",
        "manufacturer": "Nevion",
        "role": "Core OB Van Signal Router",
        "protocols": [
          "SNMP",
          "Serial Router Protocol"
        ],
        "experienceYears": 13,
        "featured": true
      },
      {
        "name": "Vislink Wireless Systems",
        "model": "COFDM RF Camera Transmitters",
        "manufacturer": "Vislink",
        "role": "Chase Vehicles & Steadicams",
        "protocols": [
          "DVB-T",
          "COFDM RF 2GHz/7GHz"
        ],
        "experienceYears": 11,
        "featured": true
      },
      {
        "name": "Evertz Frame Synchronizers",
        "model": "7700 Series Modular Processing",
        "manufacturer": "Evertz",
        "role": "Audio De-Embed & Frame Sync",
        "protocols": [
          "HD-SDI",
          "AES Audio"
        ],
        "experienceYears": 14
      }
    ]
  },
  {
    "id": "vision-mixers",
    "name": "Video Switchers & Vision Mixers",
    "iconName": "LayoutGrid",
    "description": "Production switchers, control panels, multi-format vision mixers, and multiviewers.",
    "items": [
      {
        "name": "Sony MVS-8000X",
        "model": "4 M/E 4K/3G-SDI",
        "manufacturer": "Sony",
        "role": "Flagship Production Switcher",
        "protocols": [
          "12G-SDI",
          "3G-SDI",
          "4K HDR"
        ],
        "experienceYears": 14,
        "featured": true
      },
      {
        "name": "Sony MVS-7000X / 6530",
        "model": "3 M/E & 2 M/E Compact",
        "manufacturer": "Sony",
        "role": "OB Truck Main Switcher",
        "protocols": [
          "1080p50",
          "3G-SDI"
        ],
        "experienceYears": 12,
        "featured": true
      },
      {
        "name": "Sony DVS-9000",
        "model": "Digital Production Switcher",
        "manufacturer": "Sony",
        "role": "Studio Playout Master",
        "protocols": [
          "HD-SDI",
          "SDI"
        ],
        "experienceYears": 16
      },
      {
        "name": "FOR-A HVS-2000",
        "model": "2/3 M/E Multi-Format",
        "manufacturer": "FOR-A",
        "role": "Mobile Flyaway & Heritage OB",
        "protocols": [
          "3G-SDI",
          "12G-SDI Ready"
        ],
        "experienceYears": 10,
        "featured": true
      },
      {
        "name": "FOR-A HVS-390HS",
        "model": "Compact HD Switcher",
        "manufacturer": "FOR-A",
        "role": "Sub-Mixer & Matrix Switch",
        "protocols": [
          "HD-SDI"
        ],
        "experienceYears": 8
      }
    ]
  }
];

export const TIMELINE: TimelineNode[] = [
  {
    "period": "2008 – 2014",
    "role": "Studio & Playout Systems Engineer",
    "company": "EMPC (Egyptian Media Production City) & ERTU",
    "location": "Cairo, Egypt",
    "type": "Playout & Studio",
    "description": "Engineered 24/7 master control rooms, satellite uplink telemetry, live news studios, and automated playout servers for national terrestrial and satellite television networks.",
    "achievements": [
      "Configured Pebble Beach Neptune automation and Harris Nexio playout servers for 6 continuous national channels.",
      "Calibrated multi-camera studio sets for daily live primetime news and major political broadcasts.",
      "Maintained zero downtime during critical national election live transmission events."
    ],
    "technologies": [
      "Pebble Beach Neptune",
      "Sony DVS-9000",
      "Harris Inscriber",
      "Studer Audio",
      "Tektronix WFM"
    ]
  },
  {
    "period": "2014 – 2019",
    "role": "OB Systems Engineer & CCU Specialist",
    "company": "Media Mania Production",
    "location": "Abu Dhabi, UAE",
    "type": "OB & Mobile Unit",
    "description": "Managed complete technical setup of 16-camera OB Vans, flyaway mobile production suites, long-range RF wireless links, and multi-venue sports coverage across the Gulf.",
    "achievements": [
      "Pioneered extreme-environment RF diversity tracking for 10km desert camel racing marathons (Al Dhafra Festival).",
      "Designed rapid-deployment flyaway systems cutting venue setup time by 45%.",
      "Trained and mentored junior engineering teams on CCU colorimetry and EVS highlight workflows."
    ],
    "technologies": [
      "FOR-A HVS-2000",
      "EVS XT3",
      "Grass Valley LDX",
      "Nevion Routers",
      "RTS Intercom"
    ]
  },
  {
    "period": "2019 – Present",
    "role": "Senior Broadcast & OB Engineer / CCU & EVS Lead",
    "company": "Media Art Production (MAP) & Media Mania",
    "location": "Dubai & Abu Dhabi, UAE",
    "type": "Lead Broadcast Engineer",
    "description": "Leading technical operations for tier-1 sports championships, international summits (COP28), national heritage camel races, and primetime television productions across the UAE and GCC region.",
    "achievements": [
      "Engineered COP28 international transmission matrix supporting 35+ global broadcaster feeds with zero signal dropouts.",
      "Lead CCU and EVS specialist for ADNOC UAE Pro League multi-camera 4K stadium broadcasts.",
      "Maintained 99.99% on-air uptime across 180+ consecutive live weekly primetime game show broadcasts (Emirates Draw)."
    ],
    "technologies": [
      "Sony MVS-8000X",
      "EVS XT3 Max",
      "Sony HDC-4300",
      "Evertz 5600SPG",
      "Vislink RF",
      "Pebble Beach"
    ]
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    "id": "1",
    "quote": "Samir is the definition of calm under extreme live television pressure. When our main fiber trunk was damaged 30 minutes before the presidential world address at COP28, Samir re-routed 6 CCU channels and our entire intercom matrix in under 8 minutes without a single frame dropped.",
    "author": "Khaled Al-Mansouri",
    "role": "Director of Broadcast Technical Operations",
    "organization": "Abu Dhabi Media & Host Broadcast",
    "event": "COP28 World Climate Summit",
    "avatarText": "KM"
  },
  {
    "id": "3",
    "quote": "Desert racing in 45-degree heat and sandstorms destroys standard broadcast gear. Samir engineered an RF wireless tracking setup that maintained flawless 10km link margins for 7 consecutive days. He is our first call for any high-stakes mobile OB in the GCC.",
    "author": "Markus Visser",
    "role": "Head of Mobile OB Productions",
    "organization": "Media Mania Production UAE",
    "event": "Al Dhafra National Camel Festival",
    "avatarText": "MV"
  },
  {
    "id": "2",
    "quote": "In 15 years of directing UAE Pro League football, I have never seen a CCU engineer match 16 camera angles across shifting desert stadium floodlights with the precision Samir delivers. His EVS highlight packages are cued before the referee even blows the whistle.",
    "author": "Tariq Ben Humaid",
    "role": "Senior Live Sports TV Director",
    "organization": "Abu Dhabi Sports Channel",
    "event": "UAE Pro League (ADNOC)",
    "avatarText": "TB"
  }
];

export const SHOWREEL_VIDEOS: ShowcaseVideo[] = [
  {
    "id": "cop28-world-feed",
    "title": "COP28 — World Feed Operations",
    "caption": "Plenary hall matrix & 35+ unilateral feeds",
    "thumb": "/images/showreel/cop28-world-feed.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=-UM3atf8iAI"
  },
  {
    "id": "desert-racing-rf",
    "title": "Desert Racing — RF Tracking",
    "caption": "12 km Vislink chase-cam coverage",
    "thumb": "/images/showreel/desert-racing-rf.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=558JWScMdcY"
  },
  {
    "id": "snooker-macro",
    "title": "World Snooker Masters — Macro",
    "caption": "300 fps cue-ball replay engineering",
    "thumb": "/images/showreel/snooker-macro.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=JXMvxICIj4w"
  },
  {
    "id": "uae-pro-league",
    "title": "UAE Pro League — Super Slow-Mo",
    "caption": "16-camera 4K truck & EVS replay workflow",
    "thumb": "/images/showreel/uae-pro-league.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=GzxZcTk2HT4"
  }
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    "id": "faq-common-question",
    "question": "Another question your visitors may have",
    "answer": "Example answer to the question. Feel free to customize this content with the actual information you want to provide."
  },
  {
    "id": "faq-customers-wonder",
    "question": "Something your customers often wonder about",
    "answer": "Example answer to the question. Feel free to customize this content with the actual information you want to provide."
  },
  {
    "id": "faq-overview",
    "question": "Or add sub-headings to create an overview",
    "answer": "Example answer to the question. Feel free to customize this content with the actual information you want to provide."
  },
  {
    "id": "faq-service-title",
    "question": "A title for the service you provide",
    "answer": "Example answer to the question. Feel free to customize this content with the actual information you want to provide."
  },
  {
    "id": "faq-services",
    "question": "A question about your products or services",
    "answer": "Example answer to the question. Feel free to customize this content with the actual information you want to provide."
  }
];
