/**
 * Build-time codegen: reads content/ files and generates lib/data.ts
 * so the data module has no `fs` dependency and works in client components.
 */
import fs from "fs";
import path from "path";

const CONTENT_DIR = path.join(process.cwd(), "content");
const OUTPUT = path.join(process.cwd(), "lib", "data.ts");

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
}

function readJsonDir<T>(dirPath: string): T[] {
  if (!fs.existsSync(dirPath)) return [];
  return fs
    .readdirSync(dirPath)
    .filter((f) => f.endsWith(".json"))
    .map((f) => readJson<T>(path.join(dirPath, f)));
}

// Read all content
const personalInfo = readJson<any>(path.join(CONTENT_DIR, "personalInfo.json"));
const events = readJsonDir<any>(path.join(CONTENT_DIR, "events"));
const services = readJsonDir<any>(path.join(CONTENT_DIR, "services"));
const equipment = readJsonDir<any>(path.join(CONTENT_DIR, "equipment"));
const timeline = readJsonDir<any>(path.join(CONTENT_DIR, "timeline"));
const testimonials = readJsonDir<any>(path.join(CONTENT_DIR, "testimonials"));
const showreel = readJsonDir<any>(path.join(CONTENT_DIR, "showreel"));
const faq = readJsonDir<any>(path.join(CONTENT_DIR, "faq"));

const output = `// AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
// Run \`npm run codegen\` to regenerate from content/ files.

import type {
  CaseStudy,
  ServiceTier,
  EquipmentCategory,
  TimelineNode,
  Testimonial,
  ShowcaseVideo,
  FaqItem,
} from "./types";

export interface PersonalInfo {
  name: string;
  title: string;
  subtitle: string;
  heroHeadline: string;
  tagline: string;
  portrait: string;
  showreelUrl: string;
  experienceYears: number;
  eventsCount: number;
  broadcastersCount: number;
  uptimePercentage: string;
  location: string;
  phone: string;
  email: string;
  whatsappUrl: string;
  workingHours: string;
  socials: { label: string; url: string }[];
  degree: string;
  degreeHonors: string;
  statusText: string;
  statusTextShort: string;
  statusActive: boolean;
}

export const PERSONAL_INFO: PersonalInfo = ${JSON.stringify(personalInfo, null, 2)};

export const FLAGSHIP_EVENTS: CaseStudy[] = ${JSON.stringify(events, null, 2)};

export const SERVICE_TIERS: ServiceTier[] = ${JSON.stringify(services, null, 2)};

export const EQUIPMENT_STACK: EquipmentCategory[] = ${JSON.stringify(equipment, null, 2)};

export const TIMELINE: TimelineNode[] = ${JSON.stringify(timeline, null, 2)};

export const TESTIMONIALS: Testimonial[] = ${JSON.stringify(testimonials, null, 2)};

export const SHOWREEL_VIDEOS: ShowcaseVideo[] = ${JSON.stringify(showreel, null, 2)};

export const FAQ_ITEMS: FaqItem[] = ${JSON.stringify(faq, null, 2)};
`;

fs.writeFileSync(OUTPUT, output, "utf-8");
console.log(`✓ Generated ${OUTPUT} from ${CONTENT_DIR}/`);
